AWSTemplateFormatVersion: 2010-09-09
Resources:
  ECSCluster:
    Type: "AWS::ECS::Cluster"
    Properties:
      ClusterName: JR15Cluster
  ECSTaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      ContainerDefinitions:
        - Essential: true
          Image: "willido/sample-app:jks"
          Name: gha-next
          PortMappings:
            - ContainerPort: 3000
              HostPort: 3000
              Protocol: tcp
      Cpu: 256
      ExecutionRoleArn: "arn:aws:iam::034362033405:role/ecsTaskExecutionRole"
      Family: task-definition-jr15
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      RuntimePlatform:
        OperatingSystemFamily: LINUX
  ECSService:
    Type: "AWS::ECS::Service"
    Properties:
      ServiceName: jr15-service
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - sg-0d4b7d5e3268728ef
          Subnets:
            - subnet-0ead877ef607b3e0d
      TaskDefinition: !Ref ECSTaskDefinition
