name: Deploy to Amazon ECS

on:
  pull_request:
    types:
      - opened
    branches:
      - main # main
      - "jr15*" # jr15-new jr15-this-is-new
      - "feat/**" # feat/new feat/new/button
  workflow_dispatch:
  push:
    branches:
      - main # main
      - "jr15*" # * wildcards except /
      - "feat/**" # ** wildcards, allowing /
    paths-ignore:
      - ".github/workflows/*"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
